version: '3'
services:
  user-service-db:
    image: postgres:latest
    container_name: user_service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_USER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USER_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_USER_SERVICE}
    ports:
      - "5432:5432"
    volumes:
      - user_service_data:/var/lib/postgresql/data

  inventory-service-db:
    image: postgres:latest
    container_name: inventory_service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_INVENTORY_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_INVENTORY_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_INVENTORY_SERVICE}
    ports:
      - "5433:5432"
    volumes:
      - inventory_service_data:/var/lib/postgresql/data

  order-service-db:
    image: postgres:latest
    container_name: order_service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_ORDER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ORDER_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_ORDER_SERVICE}
    ports:
      - "5434:5432"
    volumes:
      - order_service_data:/var/lib/postgresql/data

  payment-service-db:
    image: postgres:latest
    container_name: payment_service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PAYMENT_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PAYMENT_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_PAYMENT_SERVICE}
    ports:
      - "5435:5432"
    volumes:
      - payment_service_data:/var/lib/postgresql/data

volumes:
  user_service_data:
  inventory_service_data:
  order_service_data:
  payment_service_data:
